[package]
name = "rust-oauth2-oidc"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid = { version = "1.17.0", features = ["v4"] }
url = "2.5.4"
sha2 = "0.11.0-rc.0"
base64 = "0.22.1"
argon2 = "0.5"
